# Generated by Django 3.0.4 on 2021-01-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsen', '0002_onsen_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsen',
            name='efficacy',
            field=models.CharField(max_length=500),
        ),
    ]
