# Generated by Django 3.0.4 on 2021-01-16 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onsen', '0003_auto_20210102_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsen',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
