# Generated by Django 3.0.4 on 2021-01-16 14:21

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('onsen', '0004_onsen_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsen',
            name='image',
            field=stdimage.models.StdImageField(upload_to=''),
        ),
    ]
